Ensure addDocumentStartJavaScript is called on main thread (#4464)
Task/Issue URL:
https://app.asana.com/0/488551667048375/1207161413236108/f

### Description
Ensures `WebViewCompat.addDocumentStartJavaScript` is invoked on main
thread, as well as ensuring web message listeners are registered from
main thread.

From testing, it didn't seem like it mattered from where
`WebViewCompat.addDocumentStartJavaScript` was invoked, but we observed
a crash indicating there was a potential deadlock and flagging it was
called from the wrong thread.

```
java.lang.RuntimeException: Probable deadlock detected due to WebView API being called on incorrect thread while the UI thread is blocked.
```

### Steps to test this PR
- [ ] QA-optional